### ISSUE TITLE
启动的时候报错Error: A JNI error has occurred

### ISSUE THREAD

**Issue by helijia21** [liaorui/kafka-msgpack-json#6]
Exception in thread "main" java.io.IOException: Cannot run program "hash": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:100)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:114)
        at cn.learning.ConsoleConsumer$.main(ConsumerConfig.scala:57)
        at cn.learning.ConsoleConsumer.main(ConsumerConfig.scala)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 5 more

是因为在linux 里安装protobuf 吗

**Comment by liaorui** [comment]
这个错误应该跟linux有没有安装protobuf没关系。

hash好像是Linux shell内置的命令。在shell下直接输入 hash， 再回车试试，什么结果？
